name: 'ECR-Docker'
description: 'builds and pushes docker image to ecr repo'
inputs:
  dockerTag:
    description: 'Tag for docker image'
    required: true
  ecrImageName:
    description: 'Repository name for ECR'
    required: true
outputs:
  registry:
    description: 'ECR registry'
    value: ${{ steps.login-ecr.outputs.registry }}
  image:
    description: 'ECR image'
    value: '${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecrImageName }}:${{ inputs.dockerTag }}'
runs: 
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

  - name: Docker meta
    id: meta
    uses: docker/metadata-action@v4
    with:
      images: |
        ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecrImageName }}
      tags: |
        type=raw,value=${{ inputs.dockerTag }}
        type=raw,value=latest

  - uses: docker/setup-buildx-action@v2

  - name: Build and push
    uses: docker/build-push-action@v4
    with:
      context: .
      push: true
      tags: ${{ steps.meta.outputs.tags }}
      cache-from: type=gha
      cache-to: type=gha,mode=max
      provenance: false